name: Lint
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry==2.1.1
      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.12"
          cache: "poetry"
      - run: poetry install --no-root
      - name: List poetry info
        run: |
          poetry --version
          poetry env list
      - name: Pre-commit checks
        run: poetry run pre-commit run --all-files --show-diff-on-failure
