name: Run
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry==2.1.1
      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.12"
          cache: "poetry"
      - run: poetry install --no-root
      - name: List poetry info
        run: |
          poetry --version
          poetry env list
      - name: Run script
        run: poetry run python3 template_repos.py ${{ secrets.SSB_READ_TOKEN }}
